fastube/fastube/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^', include("users.urls", namespace="users")),
    url(r'^posts/', include("posts.urls", namespace="posts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fastube/posts/urls.py
from django.conf.urls import url

from posts.views import *


urlpatterns = [
    url(r'^$', PostListView.as_view(), name="list"),
    url(r'^new/$', PostCreateView.as_view(), name="create"),
    url(r'^confirm/$', PostCreateConfirmView.as_view(), name="confirm"),

    url(r'^(?P<slug>\w+)/$', PostDetailView.as_view(), name="detail"),
]

fastube/users/urls.py
from django.conf.urls import url

from users.views import *


urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name="signup"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
]

fastube/fastube/templates/partials/footer.html
<footer>
  <h1>Footer</h1>
</footer>

fastube/fastube/templates/partials/header.html
<header>
  <h1>Header</h1>

  <ul>
    {% if request.user.is_authenticated %}
      <li>
        <a href="{% url "users:logout" %}">logout</a>
      </li>
    {% else %}
      <li>
        <a href="{% url "users:login" %}">login</a>
      </li>
      <li>
        <a href="{% url "users:signup" %}">signup</a>
      </li>
    {% endif %}
  </ul>
</header>

fastube/fastube/templates/partials/messages.html
{% if messages %}
  <section id="messages">
    <ul>
      {% for message in messages %}
        <li class="{{ message.tags }}">
          <p>{{ message }}</p>
        </li>
      {% endfor %}
    </ul>
  </section>
{% endif %}