fastube/fastube/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^', include("users.urls", namespace="users")),
    url(r'^posts/', include("posts.urls", namespace="posts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fastube/posts/urls.py
from django.conf.urls import url

from posts.views import *


urlpatterns = [
    url(r'^$', PostListView.as_view(), name="list"),
    url(r'^new/$', PostCreateView.as_view(), name="create"),
    url(r'^confirm/$', PostCreateConfirmView.as_view(), name="confirm"),

    url(r'^(?P<slug>\w+)/$', PostDetailView.as_view(), name="detail"),
]

fastube/posts/models/comment.py
from django.db import models

from users.models import User


class Comment(models.Model):

    user = models.ForeignKey(User)
    post = models.ForeignKey("Post")

    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True),
    updated_at = models.DateTimeField(auto_now=True),

    def __str__(self):
        return self.content

fastube/posts/models/like.py
from django.db import models

from users.models import User


class Like(models.Model):

    user = models.ForeignKey(User)
    post = models.ForeignKey("Post")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

fastube/posts/models/post.py
from django.core.urlresolvers import reverse
from django.db import models

from users.models import User


class Post(models.Model):

    user = models.ForeignKey(User)

    hash_id = models.CharField(
        max_length=8,
        blank=True,
        null=True,
    )

    video_id = models.CharField(
        max_length=16,
    )
    video_original_title = models.CharField(
        max_length=256,
        blank=True,
        null=True,
    )

    title = models.CharField(
        max_length=256,
    )
    content = models.TextField()

    thumbnail_image = models.ImageField(
        blank=True,
        null=True,
    )

    like_user_set = models.ManyToManyField(
        User,
        related_name="like_post_set",
        through="Like",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_youtube_thumbnail_image_url(self):
        from posts.utils.youtube import get_youtube_thumbnail_image_url\
            as get_youtube_thumbnail_image_url_from_video_id
        return get_youtube_thumbnail_image_url_from_video_id(self.video_id)
    youtube_thumbnail_image_url = property(get_youtube_thumbnail_image_url)

    def get_thumbnail_image_url(self):
        if self.thumbnail_image:
            return self.thumbnail_image.url
        return self.youtube_thumbnail_image_url
    thumbnail_image_url = property(get_thumbnail_image_url)

    def get_youtube_original_url(self):
        from posts.utils.youtube import get_youtube_original_url as get_youtube_original_url_from_video_id
        return get_youtube_original_url_from_video_id(self.video_id)
    youtube_original_url = property(get_youtube_original_url)

    def get_youtube_embed_url(self):
        from posts.utils.youtube import get_youtube_embed_url as get_youtube_embed_url_from_video_id
        return get_youtube_embed_url_from_video_id(self.video_id)
    youtube_embed_url = property(get_youtube_embed_url)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={
            "slug": self.hash_id,
        })

fastube/posts/views/base.py
from django.views.generic import View

from posts.models import Post


class PostBaseView(View):
    model = Post

fastube/posts/views/create.py
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.shortcuts import render, redirect

from posts.utils import youtube


class PostCreateView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "posts/new.html",
            context={},
        )

    def post(self, request, *args, **kwargs):
        video_id = request.POST.get("video_id")
        title = request.POST.get("title")
        content = request.POST.get("content")

        thumbnail_image = request.FILES.get("thumbnail_image")

        post = request.user.post_set.create(
            video_id=video_id,
            title=title,
            content=content,
            thumbnail_image=thumbnail_image
        )

        return(redirect(post))


class PostCreateConfirmView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return redirect(reverse("posts:create"))

    def post(self, request, *args, **kwargs):
        video_id = request.POST.get("video_id")
        title = request.POST.get("title")
        content = request.POST.get("content")

        return render(
            request,
            "posts/confirm.html",
            context={
                "video_id": video_id,
                "title": title,
                "content": content,

                "youtube_original_url": youtube.get_youtube_original_url(video_id),
                "youtube_embed_url": youtube.get_youtube_embed_url(video_id),

                "youtube_thumbnail_image_url": youtube.get_youtube_thumbnail_image_url(video_id),
            },
        )

fastube/posts/views/detail.py
from django.views.generic.detail import DetailView

from .base import PostBaseView


class PostDetailView(PostBaseView, DetailView):
    template_name = "posts/detail.html"
    slug_field = "hash_id"

fastube/posts/views/list.py
from django.views.generic.list import ListView

from .base import PostBaseView


class PostListView(PostBaseView, ListView):
    template_name = "posts/list.html"
    context_object_name = "posts"

fastube/posts/templates/posts/confirm.html
{% extends "base.html" %}


{% block content %}
<h1>Confirm Post</h1>

<section>
  <iframe width="560" height="315" src="{{ youtube_embed_url }}" frameborder="0" allowfullscreen></iframe>

  <h3>{{ title }}</h3>
  <p>{{ content }}</p>

  <img src="{{ youtube_thumbnail_image_url }}" alt="{{ title }}">
  <a href="{{ youtube_original_url }}" target="_blank">유튜브 링크 바로가기</a>

  <form action="{% url "posts:create"%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
      
    <p>위의 정보로 포스트를 생성하시겠습니가?</p>
    <input type="hidden" name="video_id" value="{{ video_id }}">

    <input type="hidden" name="title" value="{{ title }}">
    <input type="hidden" name="content" value="{{ content }}">

    <p>현재의 썸네일 이미지가 마음에 안드시면 새로운 썸네일 이미지로 변경하실 수 있습니다.</p>
    <input type="file" name="thumbnail_image">

    <input type="submit">
  </form>
</section>
{% endblock %}

fastube/posts/templates/posts/detail.html
{% extends "base.html" %}
{% load pipeline %}


{% block content %}
<h1>Posts Detail</h1>

<section>
  <iframe width="560" height="315" src="{{ post.youtube_embed_url }}" frameborder="0" allowfullscreen></iframe>

  <h3>{{ post.title }}</h3>
  <h4>{{ post.video_original_title }}</h4>
  <p>{{ post.content }}</p>

  <a href="{{ post.youtube_original_url }}" target="_blank">유튜브 링크 바로가기</a>
</section>

<section id="comments-section" data-post-slug="{{ post.hash_id }}">
  <h3>Comments (<span id="comments-count">{{ post.comment_set.count }}</span>)</h3>

  <ul>
  </ul>
    
  <form>
    <input type="text" name="content" placeholder="댓글" required>
    <input type="submit" value="댓글 달기">
  </form>
</section>
{% endblock %}


{% block custom_javascripts %}
  {% javascript "posts" %}
{% endblock %}

fastube/posts/templates/posts/list.html
{% extends "base.html" %}


{% block content %}
<h1>Posts List</h1>

<section>
  <ul>
    {% for post in posts %}
    <li>
      <img src="{{ post.thumbnail_image_url }}" alt="{{ post.title }}">
      <h3>{{ post.title }}</h3>
      <p>{{ post.content }}</p>
      <a href="{{ post.get_absolute_url }}">상세페이지 바로가기</a>
    </li>
    {% endfor %}
  </ul>
</section>
{% endblock %}

fastube/posts/templates/posts/new.html
{% extends "base.html" %}


{% block content %}
<h1>New Post</h1>

<section>
  <form action="{% url "posts:confirm" %}" method="POST">
    {% csrf_token %}  
    <input type="text" name="video_id" placeholder="Youtube Video ID" required>

    <input type="text" name="title" placeholder="Title" required>
    <textarea name="content" placeholder="Content"></textarea>

    <input type="submit">
  </form>
</section>
{% endblock %}